name = "MonteCarloX"
uuid = "320e4f08-8d0f-4a8f-bb3c-13768a65d394"
version = "0.1.0"
authors = ["Johannes Zierenberg", "Martin Weigel"]

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
ProfileView = "c46f51b8-102a-5cf2-8d2c-8597cb0e0da7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SpinSystems = "8a5c3c8d-1234-5678-9abc-def012345678"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
BenchmarkTools = "1.6.3"
Distributions = "0.25"
Graphs = "1.13.2"
Plots = "1.41.3"
ProfileView = "1.10.2"
StaticArrays = "1"
StatsBase = "0.34"
julia = "1"

[extras]
HypothesisTests = "09f84164-cd44-5f33-b23f-e6b0d136a0d5"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
dev = ["BenchmarkTools"]
test = ["Test", "HypothesisTests", "BenchmarkTools"]
